### PR TITLE
Prefixed Zephyr public headers with <zephyr/..> using scripts/utils/migrate_includes.py from the Zephyr repository

### PR DESCRIPTION
**Pull request by anedergaard**
Added 'hpp' postfix to extension list in migrate_include.py see https://github.com/zephyrproject-rtos/zephyr/pull/53042 
and https://github.com/zephyrproject-rtos/zephyr/releases/tag/zephyr-v3.1.0 for details

it seems that include/zpp/error_code.hpp have had line ending changes done by the migrate_include.py script

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by lowlander** [comment]
Sorry for not noticing this pull request, I will try to merge it ASAP.

**Comment by lowlander** [comment]
> it seems that include/zpp/error_code.hpp have had line ending changes done by the migrate_include.py script

I'll fix that by hand, that shouldn't be a problem.

**Comment by lowlander** [comment]
@anedergaard I merged your changes in master.

**Comment by anedergaard** [comment]
Great @lowlander, thanks!

**Pull request closed without merging**
